/*
 * File: pos_calc.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 24-Sep-2024 12:03:42
 */

/* Include Files */
#include "pos_calc.h"
#include "rt_defines.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_atan2d_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_atan2d_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else if (rtIsInf(u0) && rtIsInf(u1)) {
    int i;
    int i1;
    if (u0 > 0.0) {
      i = 1;
    } else {
      i = -1;
    }
    if (u1 > 0.0) {
      i1 = 1;
    } else {
      i1 = -1;
    }
    y = atan2(i, i1);
  } else if (u1 == 0.0) {
    if (u0 > 0.0) {
      y = RT_PI / 2.0;
    } else if (u0 < 0.0) {
      y = -(RT_PI / 2.0);
    } else {
      y = 0.0;
    }
  } else {
    y = atan2(u0, u1);
  }
  return y;
}

/*
 * POS_CALC
 *     POS = POS_CALC(FAI1,FAI4)
 *
 * Arguments    : double fai1
 *                double fai4
 *                double pos[2]
 * Return Type  : void
 */
void pos_calc(double fai1, double fai4, double pos[2])
{
  double a;
  double b_a;
  double c_a;
  double t14;
  double t15;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     12-Aug-2024 18:28:18 */
  t2 = cos(fai1);
  t3 = cos(fai4);
  t4 = sin(fai1);
  t5 = sin(fai4);
  t6 = t2 / 25.0;
  t8 = t4 / 25.0;
  t14 = t4 * 0.0048;
  t15 = t5 * 0.0048;
  a = t8 - t5 / 25.0;
  b_a = (t3 / 25.0 - t6) + 0.04;
  c_a = t14 - t15;
  t5 = (t3 * 0.0048 - t2 * 0.0048) + 0.0048;
  t2 = a * a + b_a * b_a;
  t5 = atan((t15 - t14) +
            1.0 / (t5 + t2) * sqrt((c_a * c_a + t5 * t5) - t2 * t2)) *
       2.0;
  t2 = sin(t5);
  a = t8 + t2 * 0.06;
  t5 = (t6 + cos(t5) * 0.06) - 0.02;
  pos[0] = sqrt(a * a + t5 * t5);
  pos[1] = rt_atan2d_snf(t4 / 25.0 + t2 * 0.06, t5);
}

/*
 * File trailer for pos_calc.c
 *
 * [EOF]
 */
