/*
 * File: spd_calc.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 24-Sep-2024 12:15:06
 */

/* Include Files */
#include "spd_calc.h"
#include <math.h>

/* Function Definitions */
/*
 * SPD_CALC
 *     SPD = SPD_CALC(FAI1,FAI4,W1,W4)
 *
 * Arguments    : double fai1
 *                double fai4
 *                double w1
 *                double w4
 *                double spd[2]
 * Return Type  : void
 */
void spd_calc(double fai1, double fai4, double w1, double w4, double spd[2])
{
  double t101;
  double t10_tmp;
  double t12_tmp;
  double t2;
  double t20;
  double t21;
  double t22;
  double t23;
  double t28;
  double t3;
  double t30;
  double t31;
  double t36;
  double t4;
  double t44;
  double t47;
  double t5;
  double t52;
  double t59;
  double t64;
  double t67;
  double t68;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     12-Aug-2024 18:28:19 */
  t2 = cos(fai1);
  t3 = cos(fai4);
  t4 = sin(fai1);
  t5 = sin(fai4);
  t10_tmp = t2 / 25.0;
  t12_tmp = t4 / 25.0;
  t20 = t2 * 0.0048;
  t21 = t3 * 0.0048;
  t22 = t4 * 0.0048;
  t23 = t5 * 0.0048;
  t28 = t12_tmp - t5 / 25.0;
  t30 = (t3 / 25.0 - t10_tmp) + 0.04;
  t31 = t22 - t23;
  t36 = (t21 - t20) + 0.0048;
  t44 = t28 * t28 + t30 * t30;
  t47 = t2 * t28 * 0.08 + t4 * t30 * 0.08;
  t28 = t3 * t28 * 0.08 + t5 * t30 * 0.08;
  t52 = 1.0 / (t36 + t44);
  t30 = t52 * t52;
  t59 = sqrt((t31 * t31 + t36 * t36) - t44 * t44);
  t64 = (t23 - t22) + t52 * t59;
  t67 = atan(t64) * 2.0;
  t68 = t52 * (1.0 / t59);
  t101 =
      (t20 + (t22 + t47) * t30 * t59) -
      t68 * ((t2 * t31 * 0.0096 + t4 * t36 * 0.0096) - t44 * t47 * 2.0) / 2.0;
  t30 = (t21 + (t23 + t28) * t30 * t59) -
        t68 * ((t3 * t31 * 0.0096 + t5 * t36 * 0.0096) - t44 * t28 * 2.0) / 2.0;
  t68 = cos(t67);
  t52 = sin(t67);
  t28 = 1.0 / (t64 * t64 + 1.0);
  t4 = t68 * t28;
  t3 = t4 * t30;
  t20 = t52 * t28;
  t47 = t20 * t30;
  t22 = t12_tmp + t52 * 0.06;
  t30 = (t10_tmp + t68 * 0.06) - 0.02;
  t28 = (-t10_tmp - t68 * 0.06) + 0.02;
  t59 = t28 * t28;
  t2 = 1.0 / t28;
  t28 = 1.0 / sqrt(t22 * t22 + t30 * t30);
  t68 = t10_tmp - t4 * t101 * 0.12;
  t52 = t12_tmp - t20 * t101 * 0.12;
  spd[0] = t28 * w4 * (t22 * t3 * 0.24 - t30 * t47 * 0.24) / 2.0 +
           t28 * w1 * (t22 * t68 * 2.0 - t30 * t52 * 2.0) / 2.0;
  t30 = t59 * (1.0 / (t22 * t22 + t59));
  t28 = t22 * (1.0 / t59);
  spd[1] = t30 * w4 * (t2 * (0.0 - t3 * 0.12) + t28 * (t47 * 0.12)) -
           t30 * w1 * (t2 * t68 - t28 * t52);
}

/*
 * File trailer for spd_calc.c
 *
 * [EOF]
 */
