/*
 * File: out_calc.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 24-Sep-2024 12:19:45
 */

/* Include Files */
#include "out_calc.h"
#include <math.h>

/* Function Definitions */
/*
 * OUT_CALC
 *     OUT = OUT_CALC(F,Tp,FAI1,FAI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double fai1
 *                double fai4
 *                double out[2]
 * Return Type  : void
 */
void out_calc(double F, double Tp, double fai1, double fai4, double out[2])
{
  double a;
  double t100;
  double t101_tmp;
  double t114;
  double t118_tmp;
  double t121_tmp;
  double t163;
  double t16_tmp;
  double t171;
  double t172;
  double t173;
  double t18_tmp;
  double t30_tmp;
  double t31_tmp;
  double t32_tmp;
  double t33_tmp;
  double t51_tmp;
  double t5_tmp;
  double t62_tmp;
  double t6_tmp;
  double t77;
  double t79;
  double t7_tmp;
  double t81;
  double t82;
  double t83;
  double t84;
  double t90;
  double t91;
  double t93;
  double t94;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     12-Aug-2024 18:28:19 */
  t173 = cos(fai1);
  t5_tmp = cos(fai4);
  t6_tmp = sin(fai1);
  t7_tmp = sin(fai4);
  t16_tmp = t173 / 25.0;
  t18_tmp = t6_tmp / 25.0;
  t30_tmp = t173 * 0.0048;
  t31_tmp = t5_tmp * 0.0048;
  t32_tmp = t6_tmp * 0.0048;
  t33_tmp = t7_tmp * 0.0048;
  t163 = t18_tmp - t7_tmp / 25.0;
  t90 = (t5_tmp / 25.0 - t16_tmp) + 0.04;
  t51_tmp = t32_tmp - t33_tmp;
  t62_tmp = (t31_tmp - t30_tmp) + 0.0048;
  t77 = t163 * t163 + t90 * t90;
  t81 = t173 * t163 * 0.08 + t6_tmp * t90 * 0.08;
  t82 = t5_tmp * t163 * 0.08 + t7_tmp * t90 * 0.08;
  t79 = t163 * t163 + t90 * t90;
  t83 = t173 * t163 * 0.08 + t6_tmp * t90 * 0.08;
  t84 = t5_tmp * t163 * 0.08 + t7_tmp * t90 * 0.08;
  t90 = 1.0 / (t62_tmp + t77);
  t91 = t90 * t90;
  t93 = 1.0 / (t62_tmp + t79);
  t94 = t93 * t93;
  t100 = sqrt((t51_tmp * t51_tmp + t62_tmp * t62_tmp) - t77 * t77);
  t101_tmp = 1.0 / t100;
  t163 = t33_tmp - t32_tmp;
  t114 = t163 + t90 * t100;
  a = t163 + t93 * t100;
  t118_tmp = atan(t114) * 2.0;
  t163 = t90 * t101_tmp;
  t171 = (t30_tmp + (t32_tmp + t81) * t91 * t100) -
         t163 *
             ((t173 * t51_tmp * 0.0096 + t6_tmp * t62_tmp * 0.0096) -
              t77 * t81 * 2.0) /
             2.0;
  t172 = (t31_tmp + (t33_tmp + t82) * t91 * t100) -
         t163 *
             ((t5_tmp * t51_tmp * 0.0096 + t7_tmp * t62_tmp * 0.0096) -
              t77 * t82 * 2.0) /
             2.0;
  t81 = cos(t118_tmp);
  t121_tmp = sin(t118_tmp);
  t91 = 1.0 / (t114 * t114 + 1.0);
  t163 = t93 * t101_tmp;
  t173 = (t30_tmp + (t32_tmp + t83) * t94 * t100) -
         t163 *
             ((t173 * t51_tmp * 0.0096 + t6_tmp * t62_tmp * 0.0096) -
              t79 * t83 * 2.0) /
             2.0;
  t84 = (t31_tmp + (t33_tmp + t84) * t94 * t100) -
        t163 *
            ((t5_tmp * t51_tmp * 0.0096 + t7_tmp * t62_tmp * 0.0096) -
             t79 * t84 * 2.0) /
            2.0;
  t90 = 1.0 / (a * a + 1.0);
  t82 = t18_tmp + t121_tmp * 0.06;
  a = (t16_tmp + t81 * 0.06) - 0.02;
  t94 = t18_tmp + t121_tmp * 0.06;
  t100 = (t16_tmp + t81 * 0.06) - 0.02;
  t163 = (-t16_tmp - t81 * 0.06) + 0.02;
  t114 = t163 * t163;
  t93 = 1.0 / t163;
  t101_tmp = t81 * t90;
  t77 = t121_tmp * t90;
  t118_tmp = F * (1.0 / sqrt(t82 * t82 + a * a));
  t81 *= t91;
  t90 = t121_tmp * t91;
  t91 = t82 * (1.0 / t114);
  t163 = Tp * t114 * (1.0 / (t82 * t82 + t114));
  out[0] = t118_tmp *
               (t94 * (t16_tmp - t101_tmp * t173 * 0.12) * 2.0 -
                t100 * (t18_tmp - t77 * t173 * 0.12) * 2.0) /
               2.0 -
           t163 * (t93 * (t16_tmp - t81 * t171 * 0.12) -
                   t91 * (t18_tmp - t90 * t171 * 0.12));
  out[1] =
      t118_tmp * (t101_tmp * t94 * t84 * 0.24 - t77 * t100 * t84 * 0.24) / 2.0 +
      t163 * (t93 * (0.0 - t81 * t172 * 0.12) + t91 * (t90 * t172 * 0.12));
}

/*
 * File trailer for out_calc.c
 *
 * [EOF]
 */
